import type { User, Submission } from './types';

export const users: User[] = [
  { id: '1', name: 'Regular User', email: 'user@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d', role: 'regular' },
  { id: '2', name: 'Client User', email: 'client@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026705d', role: 'client' },
  { id: '3', name: 'Internal User', email: 'internal@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026706d', role: 'internal' },
];

export const submissions: Submission[] = [
  {
    id: 'sub1',
    userId: '1',
    title: 'Future of Fintech',
    description: 'A deep dive into blockchain, AI, and the future of financial services.',
    status: 'Approved',
    pillar: 'Professional Development',
    format: 'Panel',
    audience: 'Professionals',
    objectives: 'Understand key trends in fintech. Network with industry leaders.',
    cpe: true,
    createdAt: new Date('2023-10-01'),
  },
  {
    id: 'sub2',
    userId: '1',
    title: 'Leading with Emotional Intelligence',
    description: 'Learn how to improve your leadership skills by mastering emotional intelligence.',
    status: 'Pending',
    pillar: 'Leadership Development',
    format: 'Workshop',
    audience: 'Executives',
    objectives: 'Develop self-awareness. Enhance empathy and social skills.',
    cpe: true,
    createdAt: new Date('2023-10-15'),
  },
  {
    id: 'sub3',
    userId: '1',
    title: 'Building Your Personal Brand',
    description: 'Strategies for creating a strong personal brand in the digital age.',
    status: 'Needs Changes',
    pillar: 'Professional Development',
    format: 'Workshop',
    audience: 'Students',
    objectives: 'Define personal brand. Learn social media strategies.',
    cpe: false,
    createdAt: new Date('2023-11-05'),
  },
  {
    id: 'sub4',
    userId: '1',
    title: 'Networking for Success',
    description: 'Effective networking strategies for introverts and extroverts.',
    status: 'Rejected',
    pillar: 'Networking',
    format: 'Roundtable',
    audience: 'Students',
    objectives: 'Build confidence in networking events. Make meaningful connections.',
    cpe: false,
    createdAt: new Date('2023-11-10'),
  },
    {
    id: 'sub5',
    userId: '2',
    title: 'Corporate Responsibility in 2024',
    description: 'How companies can drive positive change.',
    status: 'Approved',
    pillar: 'Community Engagement',
    format: 'Keynote',
    audience: 'Executives',
    objectives: 'Explore CSR trends. Implement effective strategies.',
    cpe: false,
    createdAt: new Date('2023-11-20'),
  },
];
